### PR TITLE
Translate keywords in definition printers

### LINKED ISSUE #544: -dl doesn't use translation
When executing ``behat -dl --lang=nl`` I would expect to see the step types to be translated (as is also shown when doing ``behat --story-syntax --lang=nl``), but instead only the english version is shown. It would be great if they could be translated too.

Tested with Behat 3

### PR DESCRIPTION
**Pull request by WouterJ**
Fixes #544

### CODE REVIEW

**Comment by WouterJ** [comment]
Sorry @everzet, seems like I forgot this after my holiday. I've rebased now

**Comment by stof** [comment]
This is broken

**Comment by stof** [comment]
Both Travis and Scrutinizer are showing it (even though we don't have failure conditions configured on Scrutinizer so it sets the status as green)

**Comment by WouterJ** [comment]
fixed (if I'm correct)

**Pull request merged**
