### PR TITLE
Add PRIORITY constant in RowBasedTableTransformation.php

### PR DESCRIPTION
**Pull request by ablazejuk**

### CODE REVIEW

**Comment by stof** [comment]
What is the reason to add such a public constant ?

**Comment by ablazejuk** [comment]
> What is the reason to add such a public constant ?

Changed it to private

**Comment by acoulton** [comment]
@ablazejuk thanks for the PR. Please can you explain the purpose of this change? As this is a final class, and now you've made the constant private, it doesn't seem to add any benefit?

**Comment by acoulton** [comment]
@ablazejuk I'm going to close this to help us see what's still outstanding, as I don't understand the argument for the change. If I've missed something and you think it's important please feel free to reopen it.

**Pull request closed without merging**
