### PR TITLE
Fix autowiring null

### PR DESCRIPTION
**Pull request by Taluu**
Ref #1080, but not sure it really fixes it, as we still have a problem if the class is not loadable (because it doesn't exist). But IMO this is not the concern of the autowirer, but more the responsability of the organizers...

### CODE REVIEW

**Comment by Taluu** [comment]
Nevermind, solved the problem with the last commit, a `try... catch ReflectionException` was all it needed. :}

**Comment by everzet** [comment]
@Taluu you used slightly wrong assertion class. Can you update and I'll merge?

**Comment by Taluu** [comment]
You mean using the namespaced one instead ? Sure, I'll rebase while I'm at it then.

**Comment by Taluu** [comment]
Rebased and fixed the correct class. :}

**Comment by everzet** [comment]
@Taluu top one, man :)

**Comment by Taluu** [comment]
You mean in the Autowirer ? Looks good to me, It should not autowire if the key / argument exists in the index or the arguments or if the class can't be loaded ?

Unless I'm reading it wrong.

**Comment by Taluu** [comment]
A shot in the dark : Ping ? @ciaranmcnulty @stof @everzet

**Comment by ciaranmcnulty** [comment]
Thanks, @Taluu

**Pull request merged**
