### PR TITLE
Introducing Behat Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [Behat Guru](https://gurubase.io/g/behat) to Gurubase. Behat Guru uses the data from this repo and data from the [docs](https://docs.behat.org/en/latest/) to answer questions by leveraging the LLM.

In this PR, I showcased the "Behat Guru", which highlights that Behat now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable Behat Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by carlos-granados** [comment]
@kursataktas my thoughts are that while it is perfectly fine that you have built this Behat Guru, I don't think that we should endorse it from our side by providing this link. At least not until it has proven to be a tool with good acceptation within our user base, so I am not inclined to include this for now. @acoulton @ttomdewit what do you think?

**Comment by ttomdewit** [comment]
> @kursataktas my thoughts are that while it is perfectly fine that you have built this Behat Guru, I don't think that we should endorse it from our side by providing this link. At least not until it has proven to be a tool with good acceptation within our user base, so I am not inclined to include this for now. @acoulton @ttomdewit what do you think? 

I fully agree

**Comment by acoulton** [comment]
@kursataktas thanks for including Behat, I had a very quick play and I think there's potential for this to be a useful tool.

However I agree with the others that I don't think we should set a precedent of endorsing third-party tools, particularly not in the README. At the moment we don't even link direct to unofficial but long-standing Behat extensions...

**Comment by kursataktas** [comment]
Thanks for the review, everyone.

**Pull request closed without merging**
