### PR TITLE
Uniformize files coding style

### PR DESCRIPTION
**Pull request by helyakin**
Hello everyone

I'm very found of this project and try to convert everyone I know to use it when it's necessary
I've long wanted to do a contribution, and this is a complicated one (to me at list).
But beforehand I've noticed numerous inconsistencies in the coding styles files are using or use of syntax that are kinda old fashioned.

Such as array() which is useful for backward compatibility yes, but do we want to keep using it when using typed parameters in some files ?

Anyway this PR is here to discuss about this topic, and once this one will be settled I'll gladly make another one to uniformise all the typed parameters and attribute in all files.

Here are a few rule I've set using cs-fixer:
no_superfluous_phpdoc_tags: It's kind of pointless to comment the type of a typed parameter
array_syntax: use [] instead of array()
blank_line_before_statement: Some blank lines were missing between attributes
header_comment: Some file are missing the header comment
single_quote: Some file are using double quote when single is enough
visibility_required: Some function visibility were not declared
php_unit_method_casing: Enforce CamelCase case even for tests

Anyway I'll be glad to here from you before spending more time on this !

Cheers

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
Most of these changes LGTM on their own, my only historical hesitation has been the affect it has on `git blame` - is there a sensible way around that?

If we do make a change like this I'd also want to see enforcement of the rules in future by committing relevant config files and enforcing them in the GitHub workflows

**Comment by ciaranmcnulty** [comment]
Because we're using Psalm already, if some of these rules (mostly type things) can be enforced by that instead / as well it'd be good to add them to the psalm config

**Comment by ciaranmcnulty** [comment]
> my only historical hesitation has been the affect it has on git blame - is there a sensible way around that?
Aha https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view seems to address it

**Comment by ciaranmcnulty** [comment]
If you can get the build passing and add a `.git-blame-ignore-revs` file to root as described above, we can merge this sort of change.

At some point we should/could set up a CS CI job

**Comment by helyakin** [comment]
Hello @ciaranmcnulty 

First of all thank you so much for your attention regarding this PR.

I have pushed:
- [x] The .php-cs-fixer.php with some rules, we can talk furthermore about it, and the CI could be set up using the following command  `php vendor/bin/php-cs-fixer fix --using-cache=no --verbose --diff --dry-run`
- [x] Added a .git-blame-ignore-revs as requested but haven't successfully used it. I don't know what i'm doing wrong
- [x] Fixed the failing test

**Comment by helyakin** [comment]
I also think a tools like phpstan and/or php code style might do some good.
What do you think ?

**Comment by acoulton** [comment]
@helyakin thank you for your work on this. I agree that we should clean up the code style & add tooling to keep that in place in future.

However I'm going to close this because:
* It's been left stale for so long that it obviously now has a lot of merge conflicts with master.
* There are also quite a few other old PRs outstanding, some of which might not make the next release, and I don't want to make it harder to get them up to date.
* Once we have the next point release out, I think we need to review our PHP version support policy, and that might affect what code rules / refactorings we want to apply.

There's an open issue in #1306 on this topic - this PR will be useful and we'd really welcome your help when we're ready to look at that once we've caught up with the backlog a bit.

**Pull request closed without merging**
