### PR TITLE
fix php 7.1 deprecation for ReflectionType::__toString

### PR DESCRIPTION
**Pull request by Daniel-Marynicz**

### CODE REVIEW

**Comment by rpkamp** [comment]
Not that this is a duplicate of https://github.com/Behat/Behat/pull/1274

I personally like this solution better (less magic).

**Comment by Daniel-Marynicz** [comment]
i also added  https://github.com/Behat/Behat/issues/1276

**Comment by weaverryan** [comment]
Do we know that getName() was added in 7.1? If so, this looks good to me. If not, what version was it added in? If it has always existed, we could *just* use it always.

**Comment by Daniel-Marynicz** [comment]
> Do we know that getName() was added in 7.1? If so, this looks good to me. If not, what version was it added in? If it has always existed, we could _just_ use it always.
It is 
https://www.php.net/manual/en/class.reflectionnamedtype.php  
And and in this doc we have info (PHP 7 >= 7.1.0)

**Comment by Daniel-Marynicz** [comment]
> > Do we know that getName() was added in 7.1? If so, this looks good to me. If not, what version was it added in? If it has always existed, we could _just_ use it always.
> > It is
> > https://www.php.net/manual/en/class.reflectionnamedtype.php
> > And and in this doc we have info (PHP 7 >= 7.1.0)

And probably i need also check `instanceof \ReflectionNamedType`

**Comment by weaverryan** [comment]
Or you could *just* do the instanceof check and no version check?

**Comment by Daniel-Marynicz** [comment]
> Or you could _just_ do the instanceof check and no version check?

ok changed this to only instanceof  check.

**Comment by ciaranmcnulty** [comment]
Thanks!

**Pull request merged**
