### PR TITLE
Drop container-interop/container-interop from required packages

### PR DESCRIPTION
**Pull request by slavcodev**
The package has been abandoned and replaced with psr/container.

Related issues:  #1110, #1255

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
How can we do this without the BC issues?

**Comment by Taluu** [comment]
Well, the package is abandoned but it extends the right one (`psr/container`)... So maybe we could switch the asked interface for the real one, make a conflict for the version of this package and then extensions would have to require the deprecated package if they want to continue to work otherwise ?

I'm aware it's a tiny BC break, but it's best that way IMO.

**Comment by ciaranmcnulty** [comment]
I guess we could ship our own implementations?

**Comment by ciaranmcnulty** [comment]
Or maybe we can support the container if used but not `require` it in composer?

**Comment by slavcodev** [comment]
How does this break BC? Interlop interfaces extend PSR, so all end-user imlementation will still work.

**Comment by Taluu** [comment]
Extensions rely on behat, but can be transitively relying on the interlop  (big mistake, transitive dependency, I'm aware).

But then again, I think removing the require and using the psr interfaces is fine.

**Comment by slavcodev** [comment]
> can be transitively relying on the interlop

Well, these are their mistakes, those who do not properly manage dependencies.

**Comment by Taluu** [comment]
I'm one but TBH I don't really care, plan to use the proper interface if Behat uses it in the next release. :joy:

**Comment by upyx** [comment]
Hello!
Guys, it is the really annoying warning in all projects which use Behat. Why not just bump the version? If someone had been so retrograde to rely on an abandoned package, let him use the old version of Behat.

**Comment by upyx** [comment]
I've created another PR without BC break. Let's get it over with.

**Pull request closed without merging**
