### PR TITLE
Isolate getting PHP Config object to prevent var collisions

### PR DESCRIPTION
**Pull request by loic425**
Extracted from https://github.com/Behat/Behat/pull/1547

### CODE REVIEW

**Comment by loic425** [comment]
It misses one commit...

**Comment by carlos-granados** [comment]
> It misses one commit...

Yes, you need to change this to use `Closure`

**Comment by loic425** [comment]
Yes, I'll fix it tomorrow morning.

**Comment by loic425** [comment]
> Yes, you need to change this to use `Closure`

Done :)

**Review by carlos-granados — APPROVED** [review]
LGTM

**Review by acoulton — APPROVED** [review]
Thanks @loic425

**Pull request merged**
