### PR TITLE
#932 Save failed runs with suite information

### PR DESCRIPTION
**Pull request by rajeshtaneja**
Save failed runs with suite information, so
rerun run failed scenarios of suite

### CODE REVIEW

**Comment by everzet** [comment]
Can you provide a test case? Simple version of "Steps to reproduce" section from your issue would work nicely!

**Comment by rajeshtaneja** [comment]
Information has been added https://github.com/Behat/Behat/issues/932

## Steps to reproduce:
> git clone https://github.com/rajeshtaneja/MinkExtension-example.git
cd MinkExtension-example
curl http://getcomposer.org/installer | php
php composer.phar install

#### Run behat
>git checkout multiplesuites
bin/behat

* Only one feature file is executed with 3 scenarios.
* Check /tmp/behat_rerun_cache/xxxx.scenarios and you will see only 1 scenario listed

##### Re-run behat
>bin/behat --rerun

You will observe features are executed twice, as temp context doesn't have search.feature it should only be executed once.

**Comment by everzet** [comment]
It is not a cost effective test case if it is not automated :) Can you write a representative feature file under `features/` folder?

**Comment by rajeshtaneja** [comment]
Our features are distributed in different modules, so if plugin is installed it will have it's own features and context.

Sorry I didn't get the cost factor problem involved. Can you please explain. Other then the current solution  , I can override scenario list locator to check if it's a json file or just scenarios and return feature accordingly.

**Comment by everzet** [comment]
@rajeshtaneja write an automated test case (living under `features/` folder) as part of this PR.

**Comment by rajeshtaneja** [comment]
Thanks @everzet ,

Added testcase.

**Comment by everzet** [comment]
@rajeshtaneja that's awesome! Thank you.

**Comment by rajeshtaneja** [comment]
Thank you for keeping up the awesome work. 

Sorry, I didn't get your comment earlier about the testcase. I was reading between the lines....

Can you please let us know due date for 3.2.0

**Comment by everzet** [comment]
@rajeshtaneja you can expect the RC1 in the next couple of days.

**Comment by rajeshtaneja** [comment]
Thanks @everzet

**Pull request merged**
