### PR TITLE
Add PHP 5.3 to travis

### PR DESCRIPTION
**Pull request by caciobanu**
This will catch issues like #1035.

### CODE REVIEW

**Comment by caciobanu** [comment]
Build is failing due to short array syntax. Do you want me to fix those also, in this PR ?

**Comment by Taluu** [comment]
It was intentionnally removed from the test matrix in https://github.com/Behat/Behat/commit/f3e1481b6fca205ec9e0d1242be3d49af538624d and https://github.com/Behat/Behat/commit/cf47261ea5a2e7376dafa307b3783b8768795fca

**Comment by Taluu** [comment]
And the ticket you are mentionning is not related (at all) to php 5.3. The short array syntax is not used because of consistency across all usages in the project.

**Comment by caciobanu** [comment]
So 5.3 is not supported anymore? If yes maybe composer.json should be updated?

**Comment by everzet** [comment]
We didn't explicitly drop the support, but we stopped bothering with it as much. Version was dropped from the matrix because newer Travis VMs don't even have 5.3.

Bottom line: Behat should still work on PHP 5.3, but it might get broken from version to version (unintentionally). Next major will kill support altogether.

**Pull request closed without merging**
