### PR TITLE
Allow to import with wildcard path

### LINKED ISSUE #1097: Allow to import with wildcard path
Importing configuration files with wildcard option would allow to import main/parent config to import generic configurations available. e.g. module/*/behat.yml would allow to import any drupal module with behat configuration to import from site's behat.yml.

### PR DESCRIPTION
**Pull request by vijaycs85**
Fixes #1097

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
@vijaycs85 This looks good, is it possible to also get it working on older/newer Symfony Finder versions?

**Comment by vijaycs85** [comment]
@ciaranmcnulty sure, let me know which versions should be covered, I will check them.

**Comment by Taluu** [comment]
If I had to guess, it would be ^2.8, ^3.4 and ^4.0. :}

**Comment by pamil** [comment]
After #1299 is merged, the supported Finder versions should be `^4.4|^5.0`, which should make it simpler. @vijaycs85 would you like to give it a shot?

Apart from that, we'd also need a scenario for those wildcard paths.

**Comment by vijaycs85** [comment]
@pamil sure, should we wait for #1299 to get in?

**Comment by pamil** [comment]
@vijaycs85 yeah, I think it'd be the best to wait for it indeed.

**Comment by pamil** [comment]
@vijaycs85 #1299 has just been merged :)

**Comment by mnocon** [comment]
Hi @vijaycs85! Are you still interested in working on this issue? 

I'm interested in this feature as well, if you don't have time I can try to prepare my own PR.

**Comment by ciaranmcnulty** [comment]
Closing due to inactivity lately

**Pull request closed without merging**
