### PR TITLE
Return type transformations

### PR DESCRIPTION
**Pull request by everzet**
Second half of #863 This PR introduces two new transformations:

## 1. Pure type-based based transformation for php7

Pure typed transformation, that matches all type-hints:

```php
/**
 * @Transform
 */
public function toUser($user) : User
{
    return User::fromString($user);
}
```

## 2. Both named and typed transformation for php7

In case you want to handle specific case differently, you'll be able to use both variable name AND type. Transformation will get applied ONLY if both match the argument:

```php
/**
 * @Transform :name
 */
public function toNamedUser($name) : User
{
    return User::named($name);
}
```

## Order of application

These will be applied in following order: "name & return type", "just return type", "just name". The first found wins.

### CODE REVIEW

**Comment by everzet** [comment]
Just realised I've made a BC break in the `Transformation` interface. Will need to further refactor...

**Comment by sroze** [comment]
So we don't care about introducing a BC break in the `SimpleArgumentTransformation` interface? It can probably be avoided quite easily by introducing a new one I think, wouldn't it be better? Or are you planning to introduce many BC breaks that would force you to release a new major version soon?

**Comment by everzet** [comment]
@sroze good catch. That totally wasn't been intentional.

**Comment by everzet** [comment]
`SimpleArgumentTransformation` interface didn't exist until this work. So we're all good :)

**Comment by pamil** [comment]
Is it planned to add support for PhpDoc `@return` tag to the core if transformation does not have a return type? If so, I'd love to add it.

**Comment by everzet** [comment]
@pamil I'm not planning on adding it, but if you want to - please go ahead.

**Comment by pamil** [comment]
All right then, I'll try to send a PR this week.

**Comment by nifr** [comment]
@pamil Did you start with the PR to add `@return` phpdoc? There's no reference in here and I can't find it in open PRs. I think this feature would be a great addition to behat.

**Pull request merged**
