### PR TITLE
Dropping support for PHP <5.5

### PR DESCRIPTION
**Pull request by Sam-Burns**
Ref https://github.com/Behat/Behat/issues/821

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
I think this should wait for a major version

**Comment by Sam-Burns** [comment]
@ciaranmcnulty Don't object to you bumping the major version number instead of the minor version, but I don't think that's really necessary, and I know that isn't how Sensiolabs like to do things.

To be responsible, support for PHP 5.3 should have been dropped in the summer of '14, so I wouldn't delay any longer.  Also, regarding advertising the tool on Packagist as 'Scenario-oriented BDD framework for PHP 5.3', I think more could be done to make it sound contemporary and relevant.

**Comment by ciaranmcnulty** [comment]
I don't think SemVer requires a major version bump so it's up to @everzet

**Comment by Taluu** [comment]
> I don't think SemVer requires a major version bump so it's up to @everzet

It actually doesn't :

> What should I do if I update my own dependencies without changing the public API?
>
> That would be considered compatible since it does not affect the public API. Software that explicitly depends on the same dependencies as your package should have their own dependency specifications and the author will notice any conflicts. Determining whether the change is a patch level or minor level modification depends on whether you updated your dependencies in order to fix a bug or introduce new functionality. I would usually expect additional code for the latter instance, in which case it's obviously a minor level increment.

But if the public api changes, it does need to bump a minor / major (Depending on how the break is made).

And :+1:

**Comment by Sam-Burns** [comment]
Thanks @Taluu. Together, we can end PHP 5 in our lifetime ;-)

**Comment by stof** [comment]
See my comment on the issue for the actual implication of this change

**Comment by everzet** [comment]
Provided an argument in the related issue. Closing this PR as it is non-merge able anyways ATM. If the discussion in related issue will arrive at conclusion of progressing with this PR - feel free to rebase and reopen it.

**Pull request closed without merging**
