### PR TITLE
removal of old versions for the update to sf5

### PR DESCRIPTION
**Pull request by flug**
pre-pull-request for the removal of versions not maintained by symfony and the removal of old versions of php that are no longer maintained. This will facilitate the migration of behat code to the latest symfony 5 components. 

pr ref : https://github.com/Behat/Behat/pull/1247

### CODE REVIEW

**Comment by Taluu** [comment]
That would be awesome to stop supporting php 5... But alas, it's not planned until at least 4.0. Unless it has changed since then (Let a man dream 😂 )

**Comment by flug** [comment]
@Taluu it might just be the beginning of version 4  :stuck_out_tongue_winking_eye:

**Comment by ciaranmcnulty** [comment]
What @Taluu said, basically

**Comment by flug** [comment]
@ciaranmcnulty is the removal of php 5.* critical for you or is it really necessary to remove it? to know if my other pull request should be modified or not?

**Comment by rpkamp** [comment]
So when is 4.x planned?

**Comment by pamil** [comment]
Do we really need to wait for 4.x to remove PHP 5 support? It is not a BC break: https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

**Comment by Taluu** [comment]
It's not on the sense of semver but that's what is applied on Behat (and most projects from symfony ecosystem)... :{

**Comment by ciaranmcnulty** [comment]
As I said, we're not planning to drop support yet

**Pull request closed without merging**
