### PR TITLE
Fix for #1108: Serialization of 'Closure' is not allowed

### PR DESCRIPTION
**Pull request by philtweir**
Allows for changes in Symfony serialization in 4.x, where `json_encode` has been replaced by `serialize` and an error is thrown if a closure is found. This replaces the service container object as a Definition argument with a Symfony DI Reference that can be serialized.

### CODE REVIEW

**Comment by philtweir** [comment]
Having had a look through the features, I'm not too sure what the best approach for a test for this would be, but happy to take some direction.

**Comment by philtweir** [comment]
For context, in case anyone is having similar issues: Behat-Laravel-Extension#78 was what led to this PR - in the meantime, following the instructions there should (as a stop-gap) get Behat working for Laravel >=5.6.

**Comment by titopixelfusion** [comment]
It would be great to merge this PR

**Comment by ciaranmcnulty** [comment]
Yep looks good, thank you

**Comment by ciaranmcnulty** [comment]
Thanks @philtweir!

**Comment by philtweir** [comment]
Thanks @ciaranmcnulty !

**Pull request merged**
