### PR TITLE
Add .editorconfig file

### PR DESCRIPTION
**Pull request by chapeupreto**
Add .editorconfig file

See: https://editorconfig.org/

### CODE REVIEW

**Comment by ciaranmcnulty** [comment]
I don't see a strong reason for this, sorry

**Comment by stof** [comment]
@ciaranmcnulty I actually find this quite convenient as it avoids having to reconfigure manually the formatting setting of the IDE for new contributors (is this project using 2 spaces or 4 spaces in Yaml files ? Editorconfig handles that automatically)

**Comment by chapeupreto** [comment]
It is worth mentioning that big projects are already using such a file, e.g., `Composer`:

https://github.com/composer/composer/blob/main/.editorconfig

Why not use it here as well? I mean, what harm can it do anyways?

**Comment by ciaranmcnulty** [comment]
ok, I'm convinced. I can't re-open 'cause the branch is deleted

**Comment by chapeupreto** [comment]
@ciaranmcnulty my bad! I submitted another PR here: https://github.com/Behat/Behat/pull/1418

**Pull request closed without merging**
